// check.js — functional checks of the assembled site in a simulated DOM (jsdom)
const {JSDOM}=require('jsdom');const fs=require('fs');
const file=process.argv[2]||'../combate.html';
const html=fs.readFileSync(file,'utf8').replace(/<script src="https:[^"]+"><\/script>/,'');
const dom=new JSDOM(html,{runScripts:'dangerously',url:'file:///Desktop/combate.html#/method'});
const w=dom.window,d=w.document;w.prompt=()=>'x';
let ok=0,fail=0;const t=(n,c)=>{c?ok++:fail++;console.log((c?'ok  ':'FAIL')+' '+n)};
setTimeout(()=>{
  t('starts in English',d.documentElement.lang==='en'&&d.querySelector('#nav a[href="#/method"]').textContent==='Method');
  t('method view on at load',d.querySelector('#v-method').classList.contains('on'));
  t('code embedded',d.querySelector('#code-seg').textContent.includes('def segment_page'));
  t('pixel table rows',d.querySelectorAll('#pixtable tr').length===8);
  t('region table rows',d.querySelectorAll('#regiontable tr').length>1);
  t('extra figs',d.querySelectorAll('#seg-extra figure').length===3);
  t('ocr sample',d.querySelector('#ocr-sample').textContent.startsWith('As Forças'));
  t('figures have src',[...d.querySelectorAll('#v-method img')].every(i=>i.src.startsWith('data:image')));
  d.querySelector('#lang').click();
  t('switch to Portuguese',d.documentElement.lang==='pt-PT');
  t('nav translated',d.querySelector('#nav a[href="#/method"]').textContent==='Método');
  t('method heading translated',d.querySelector('#s3 h2').textContent==='Separar o texto dos desenhos');
  t('figures still have src after switch',[...d.querySelectorAll('#v-method img')].every(i=>i.src.startsWith('data:image')));
  t('code still embedded after switch',d.querySelector('#code-ocr').textContent.includes('def read_page'));
  t('region table translated',d.querySelector('#regiontable th').textContent==='Primeira etiqueta');
  t('title translated',d.title.includes('Leitura por máquina'));
  d.querySelector('#nav a[href="#/issues"]').click();
  t('issues view',d.querySelector('#v-issues').classList.contains('on'));
  t('51 cards',d.querySelectorAll('#issuegrid .card').length===51);
  t('card buttons in Portuguese',d.querySelector('#issuegrid .card a').textContent==='Ler');
  d.querySelector('#issuegrid .card a').click();
  t('issue view',d.querySelector('#v-issue').classList.contains('on'));
  t('issue title Portuguese',d.querySelector('#iv-title').textContent==='Número 1');
  t('issue gallery tiles',d.querySelectorAll('#iv-gal .tile').length===3);
  d.querySelector('#lang').click();
  t('back to English keeps issue',d.querySelector('#iv-title').textContent==='Issue 1');
  d.querySelector('#nav a[href="#/visuals"]').click();
  t('8 tiles',d.querySelectorAll('#galgrid .tile').length===8);
  d.querySelector('#galgrid .tile').click();
  t('lightbox opens',d.querySelector('#lb').classList.contains('on'));
  d.querySelector('#lb-close').click();
  d.querySelector('#nav a[href="#/about"]').click();
  t('about view',d.querySelector('#v-about').classList.contains('on'));
  d.querySelector('.brand').click();
  t('home view',d.querySelector('#v-home').classList.contains('on'));
  t('hero src',d.querySelector('#hero-img').src.startsWith('data:image'));
  w.location.hash='#/issue/20';w.dispatchEvent(new w.Event('hashchange'));
  t('hashchange to issue 20',d.querySelector('#iv-title').textContent==='Issue 20');
  d.querySelector('#nav a[href="#/method"]').click();
  d.querySelector('[data-jump="s3"]').click();
  t('stage jump keeps method',d.querySelector('#v-method').classList.contains('on'));
  console.log(ok+' passed, '+fail+' failed');process.exit(fail?1:0);
},800);
